config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'welcome#index'
  get 'update_increases', to: 'welcome#update_increases', as: 'update_increases'
  get 'country/confirmed/:country', to: 'covid_info_country#confirmed'
  get 'country/recovered/:country', to: 'covid_info_country#recovered'
  get 'country/deaths/:country', to: 'covid_info_country#deaths'

  get 'global/confirmed', to: 'covid_info_global#confirmed'
  get 'global/recovered', to: 'covid_info_global#recovered'
  get 'global/deaths', to: 'covid_info_global#deaths'
  get 'global/daily', to: 'covid_info_global#daily'
  

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/covid_daily_status.rb
class CovidDailyStatus < ApplicationRecord
  before_save :create_daily_increase

  private

  def create_daily_increase
    last_daily_status = CovidDailyStatus.last
    
    DailyIncrease.create(
      confirmed: confirmed - last_daily_status.confirmed,
      recovered: recovered - last_daily_status.recovered,
      deaths:    deaths - last_daily_status.deaths
    )
  end
end

app/models/daily_increase.rb
class DailyIncrease < ApplicationRecord
  scope :last_filled_increases, -> { where('confirmed > 0 OR recovered > 0 OR deaths > 0').last }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/covid_info_country_controller.rb
class CovidInfoCountryController < ApplicationController
  before_action :set_country
  before_action :set_covid_country_request

  def confirmed
    @confirmed = @country_status.confirmed
  end

  def recovered
    @recovered = @country_status.recovered
  end

  def deaths
    @deaths = @country_status.deaths
  end

  private

  def set_country
    @params_country = params.permit(:country)
  end

  def set_covid_country_request
    @country_status = CovidStatus::CountryCovidStatus.new(@params_country['country'])
  end
end

app/controllers/covid_info_global_controller.rb
class CovidInfoGlobalController < ApplicationController
  before_action :set_covid_global_request

  def confirmed
    @confirmed = @global_status.confirmed
  end

  def recovered
    @recovered = @global_status.recovered
  end

  def deaths
    @deaths = @global_status.deaths
  end

  def daily
    @daily = @global_status.daily
  end

  private

  def set_covid_global_request
    @global_status = CovidStatus::GlobalCovidStatus.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_covid_global_request

  def index
    @general_infos = @global_status.general.slice('confirmed', 'deaths', 'recovered')
    @daily_increase = DailyIncrease.last_filled_increases
  end

  def update_increases
    DailyStatusJob.perform_async
    flash[:alert] = "Updated increases!"
    redirect_to root_path
  end

  private

  def set_covid_global_request
    @global_status = CovidStatus::GlobalCovidStatus.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/covid_info_country_helper.rb
module CovidInfoCountryHelper
end

app/helpers/covid_info_global_helper.rb
module CovidInfoGlobalHelper
  def parse_time(date)
    Time.at(date.to_i / 1000).strftime('%d/%m/%Y %H:%M:%S')
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/covid_info_country/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">COVID INFO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Confirmed', global_confirmed_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Recovered', global_recovered_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Deaths', global_deaths_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Daily', global_daily_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/covid_info_country/confirmed.html.erb
<h1 class="text-white">Confirmed <%= params['country'].upcase %></h1>

<div class="table-responsive">
  <table class="table table-hover table-bordered bg-white">
    <thead class="thead-dark">
      <tr>
        <th>Country</th>
        <th>City</th>
        <th>Confirmed</th>
        <th>Recovered</th>
        <th>Deaths</th>
        <th>Last update</th>
      <tr>
    </thead>

    <tbody>
      <% @confirmed.each do |confirmed| %>
        <tr>
          <td><%= confirmed['countryRegion'] %></td>
          <td><%= confirmed['provinceState'] %></td>
          <td class="text-danger font-weight-bold"><%= confirmed['confirmed'] %></td>
          <td><%= confirmed['recovered'] %></td>
          <td><%= confirmed['deaths'] %></td>
          <td><%= parse_time(confirmed['lastUpdate']) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/covid_info_country/deaths.html.erb
<h1 class="text-white">Deaths <%= params['country'].upcase %></h1>

<div class="table-responsive">
  <table class="table table-hover table-bordered bg-white">
    <thead class="thead-dark">
      <tr>
        <th>Country</th>
        <th>City</th>
        <th>Confirmed</th>
        <th>Recovered</th>
        <th>Deaths</th>
        <th>Last update</th>
      <tr>
    </thead>

    <tbody>
      <% @deaths.each do |deaths| %>
        <tr>
          <td><%= deaths['countryRegion'] %></td>
          <td><%= deaths['provinceState'] %></td>
          <td><%= deaths['confirmed'] %></td>
          <td><%= deaths['recovered'] %></td>
          <td class="text-danger font-weight-bold"><%= deaths['deaths'] %></td>
          <td><%= parse_time(deaths['lastUpdate']) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/covid_info_country/recovered.html.erb
<h1 class="text-white">Recovered <%= params['country'].upcase %></h1>

<div class="table-responsive">
  <table class="table table-hover table-bordered bg-white">
    <thead class="thead-dark">
      <tr>
        <th>Country</th>
        <th>City</th>
        <th>Confirmed</th>
        <th>Recovered</th>
        <th>Deaths</th>
        <th>Last update</th>
      <tr>
    </thead>

    <tbody>
      <% @recovered.each do |recovered| %>
        <tr>
          <td><%= recovered['countryRegion'] %></td>
          <td><%= recovered['provinceState'] %></td>
          <td><%= recovered['confirmed'] %></td>
          <td class="text-danger font-weight-bold"><%= recovered['recovered'] %></td>
          <td><%= recovered['deaths'] %></td>
          <td><%= parse_time(recovered['lastUpdate']) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/covid_info_global/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to 'COVID INFO', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Confirmed', global_confirmed_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Recovered', global_recovered_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Deaths', global_deaths_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Daily', global_daily_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/covid_info_global/confirmed.html.erb
<h1 class="text-white">Confirmed</h1>

<div class="table-responsive">
  <table class="table table-hover table-bordered bg-white">
    <thead class="thead-dark">
      <tr>
        <th>Country</th>
        <th>City</th>
        <th>Confirmed</th>
        <th>Last update</th>
      <tr>
    </thead>

    <tbody>
      <% @confirmed.each do |confirmed| %>
        <tr>
          <td><%= confirmed['countryRegion'] %></td>
          <td><%= confirmed['provinceState'] %></td>
          <td><%= link_to confirmed['confirmed'], "/country/confirmed/#{confirmed['iso3']}" %></td>
          <td><%= parse_time(confirmed['lastUpdate']) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/covid_info_global/daily.html.erb
<h1 class="text-white">Daily</h1>

<div class="table-responsive">
  <table class="table table-hover table-bordered bg-white">
    <thead class="thead-dark">
      <tr>
        <th>Total Confirmed</th>
        <th>Total Recovered</th>
        <th>Mainland China</th>
        <th>Report Date</th>
      <tr>
    </thead>

    <tbody>
      <% @daily.each do |daily| %>
        <tr>
          <td><%= daily['totalConfirmed'] %></td>
          <td><%= daily['totalRecovered'] %></td>
          <td><%= daily['mainlandChina'] %></td>
          <td><%= daily['reportDate'] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/covid_info_global/deaths.html.erb
<h1 class="text-white">Deaths</h1>

<div class="table-responsive">
  <table class="table table-hover table-bordered bg-white">
    <thead class="thead-dark">
      <tr>
        <th>Country</th>
        <th>City</th>
        <th>Deaths</th>
        <th>Last update</th>
      </tr>
    </thead>

    <tbody>
      <% @deaths.each do |death| %>
        <tr>
          <td><%= death['countryRegion'] %></td>
          <td><%= death['provinceState'] %></td>
          <td><%= link_to death['deaths'], "/country/deaths/#{death['iso3']}" %></td>
          <td><%= parse_time(death['lastUpdate']) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/covid_info_global/recovered.html.erb
<h1 class="text-white">Recovered</h1>

<div class="table-responsive">
  <table class="table table-hover table-bordered bg-white">
    <thead class="thead-dark">
      <tr>
        <th>Country</th>
        <th>City</th>
        <th>Recovered</th>
        <th>Last update</th>
      </tr>
    </thead>

    <tbody>
      <% @recovered.each do |recovered| %>
        <tr>
          <td><%= recovered['countryRegion'] %></td>
          <td><%= recovered['provinceState'] %></td>
          <td><%= link_to recovered['recovered'], "/country/recovered/#{recovered['iso3']}" %></td>
          <td><%= parse_time(recovered['lastUpdate']) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Covid Info</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'https://bit.ly/2J735eH' %>

    <style>
      body {
        background-color: #688299;
      }
    </style>
  </head>

  <body>
    <%= render partial: "navbar" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to 'COVID INFO', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Confirmed', global_confirmed_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Recovered', global_recovered_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Deaths', global_deaths_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Daily', global_daily_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/welcome/_status_card.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= kind %></h5>
    <p class="card-text">Total: <%= total %></p>
    <p class="card-text">Daily increase: <%= daily_increase %></p>
    <%= link_to 'More info', path, class: 'btn btn-warning'%>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-sm">
    <%= render partial: 'status_card', locals: { 
      kind: 'Confirmed',
      total: @general_infos.dig('confirmed', 'value'),
      daily_increase: @daily_increase&.confirmed,
      path: global_confirmed_path
    } %>
  </div>

  <div class="col-sm">
    <%= render partial: 'status_card', locals: { 
      kind: 'Recovered',
      total: @general_infos.dig('recovered', 'value'),
      daily_increase: @daily_increase&.recovered,
      path: global_recovered_path
    } %>
  </div>

  <div class="col-sm">
    <%= render partial: 'status_card', locals: { 
      kind: 'Deaths',
      total: @general_infos.dig('deaths', 'value'),
      daily_increase: @daily_increase&.deaths,
      path: global_deaths_path
    } %>
  </div>
</div>

<% if flash['alert'].present? %>
  <script>
    toastr.success(
      "<%= flash['alert'] %>",
      'Success'
  );
  </script>
<% end %>

<%= link_to update_increases_path, class: 'btn btn-light mt-4 mb-5'	do %>
  <%= octicon "sync", height: '20' %>
<% end %>